### PR TITLE
adding compatibility for laravel 10 by adding support for PHP 8.1

### PR DESCRIPTION
**Pull request by swapnilsarwe**
- Adding support for PHP 8.1 to make it compatible with Laravel 10 [Laravel 10 support PHP 8.1](https://laravel.com/docs/10.x/releases)
- Updating Test Matrix to avoid Laravel 11 with PHP 8.1

### CODE REVIEW

**Comment by swapnilsarwe** [comment]
Hey @afatmustafa ,
Since your README.md read support for laravel 10, I have added support for PHP 8.1.

Since Laravel 10 is still active. Having complete support for it would be appreciated.

**Comment by swapnilsarwe** [comment]
Once you feel good about this PR and merge it, we should also get it added on blade-ui-kit.com website.

**Comment by afatmustafa** [comment]
Hey @swapnilsarwe, thanks for the contribution.

**Comment by swapnilsarwe** [comment]
> Once you feel good about this PR and merge it, we should also get it added on blade-ui-kit.com website.

Have raised a PR for adding this iconset on blade-ui-kit.com website
https://github.com/blade-ui-kit/blade-ui-kit.com/pull/168

**Comment by afatmustafa** [comment]
Thanks for your effort @swapnilsarwe .

**Pull request merged**
